route:
    repeat_interval: 30m
    group_interval: 30m
    receiver: 'rocketchat'

receivers:
    - name: 'rocketchat'
      webhook_configs:
          - send_resolved: false
            url: 'curl -X POST -H 'Content-Type: application/json' --data '{"icon_url":"https://avatars3.githubusercontent.com/u/48142654?s=460&v=4","text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}' http://noc.jacare.tech:3080/hooks/undefined/undefined'


### IF YOU WANT USE SLACK, UNCOMMENT THE LINES BELLOW AND COMMENT THE LINES ABOVE
### REMEMBER, IF YOU WANT USE SLACK, YOU DON'T NEED THE MONGO AND ROCKETCHAT SERVICES, SO YOU CAN REMOVE THIS SERVICES FROM docker-compose FILE.
### PUT YOUR INFORMATION AS USERNAME, CHANNEL AND THE INCOMMING WEBHOOK

#route:
#   receiver: 'slack'
#
#receivers:
#   - name: 'slack'
#     slack_configs:
#        - send_resolved: true
#          username: 'YOUR USERNAME'
#          channel: '#YOURCHANNEL'
#          api_url: 'INCOMMING WEBHOOK'
