{
 "title": "Golden Signals Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_vts_server_requests_total[1d]))  "
    }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code!~\"5xx\"}[1d]))/sum(rate(nginx_vts_server_requests_total[1d]))"
    }
   ]
  },
  {
   "title": "% de Erros",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code=\"5xx\"}[1d]))/sum(rate(nginx_vts_server_requests_total[1d]))"
    }
   ]
  },
  {
   "title": "Latência - Percentil 50",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_vts_server_request_duration_seconds_bucket[1d])) by (le))"
    }
   ]
  },
  {
   "title": "Latência - Percentil 90",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_vts_server_request_duration_seconds_bucket[1d])) by (le))"
    }
   ]
  },
  {
   "title": "Latência - Percentil 99",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_vts_server_request_duration_seconds_bucket[1d])) by (le))"
    }
   ]
  }
 ]
}