{
 "title": "System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Serviços Ativos",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{job=\"netdata\"}",
     "legendFormat": "{{job}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Interface ens4",
   "type": "graph",
   "description": "Interface de rede upload e download",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{chart=\"net.ens4\",dimension=\"received\",family=\"ens4\",instance=\"noc.jacare.tech:19999\",job=\"netdata\"}/8",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_net_net_kilobits_persec_average{chart=\"net.ens4\",dimension=\"sent\",family=\"ens4\",instance=\"noc.jacare.tech:19999\",job=\"netdata\"}/8",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "System_CPU_Master",
   "type": "graph",
   "description": "Média percentual da CPU do sistema - netdata",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "netdata_system_cpu_percentage_average{chart=\"system.cpu\",dimension=\"user\",family=\"cpu\",instance=\"noc.jacare.tech:19999\",job=\"netdata\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_system_cpu_percentage_average{chart=\"system.cpu\",dimension=\"system\",family=\"cpu\",instance=\"noc.jacare.tech:19999\",job=\"netdata\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  }
 ]
}